blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/thu-san/next-navigation-progress/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/thu-san/next-navigation-progress#readme
    about: Check out the documentation for usage examples